##############################################################################
# Build global options
# NOTE: Can be overridden externally.
#


# Imported source files and paths


# C++ sources that can be compiled in ARM or THUMB mode depending on the global
# setting.
CPPSRC += main.cpp \
	logicdata_csv_reader.cpp


INCDIR += \


include unit_test_rules.mk
